### ISSUE TITLE
pre-commit error report after PR #210

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#213]
After merging PR #210, I met the following error of clang-tidy in `pre-commit run --all-files`
```
clang-tidy...............................................................Failed
- hook id: clang-tidy
- exit code: 1

/Users/togo/code/atztogo/spglib/src/spglib.c:60:10: error: 'version.h' file not found [clang-diagnostic-error]
#include "version.h"
```
If I understand correctly, `version.h` is generated by cmake. So its complain is correct. Is there any iade to avoid this error in clang-tidy?

Ping @LecrisUT.

**Comment by LecrisUT** [comment]
Hmm, let me check my clion environment. Basically we should call cmake and perform clang-tidy in the build directory. Need to check if there's flags to be set or documented cmake examples

**Comment by LecrisUT** [comment]
https://stackoverflow.com/a/68014682

**Comment by LecrisUT** [comment]
Note-to-self. Add documentation about [pre-commit](https://pre-commit.com/)
