### PR TITLE
Fix pre-commit

### LINKED ISSUE #213: pre-commit error report after PR #210
After merging PR #210, I met the following error of clang-tidy in `pre-commit run --all-files`
```
clang-tidy...............................................................Failed
- hook id: clang-tidy
- exit code: 1

/Users/togo/code/atztogo/spglib/src/spglib.c:60:10: error: 'version.h' file not found [clang-diagnostic-error]
#include "version.h"
```
If I understand correctly, `version.h` is generated by cmake. So its complain is correct. Is there any iade to avoid this error in clang-tidy?

Ping @LecrisUT.

### PR DESCRIPTION
**Pull request by LecrisUT**
Closes #213

Note that there are some pre-commit that have not been fixed.

~~(Currently depends on #214 because I didn't rebase that out)~~

### CODE REVIEW

**Comment by LecrisUT** [comment]
@atztogo Can you help or assign someone to help with some of the C errors like `malloc` etc.?

File: .pre-commit-config.yaml [hunk 1]
```diff
@@ -5,31 +5,18 @@ default_language_version:
...
   hooks:
-  - id: clang-format
-    args: ["-i", "--style=file"]  # Use style set in .clang-format
-    files: |
-      (?x)^(
-        ^src/.+\.(c|h)|
-        ^test/.+\.(c|h)|
-        ^python/_spglib.c
-      )$
-    exclude: src/msg_database.c  # Skip too large file to wait every time
```
Comment (lan496) [inline .pre-commit-config.yaml:19]: @LecrisUT Thank you for your many efforts to improve spglib's CMake build!
Can you retain this line 19 to skip src/msg_database.c because it takes too long time to wait every time?

**Comment by atztogo** [comment]
> to help with some of the C errors like `malloc` etc.?

This part, I don't understand. What do you want? Have you met `malloc` errors?

File: .pre-commit-config.yaml (hunk 1 above)
Comment (LecrisUT) [reply .pre-commit-config.yaml:19]: Thanks for letting me know about this

**Comment by LecrisUT** [comment]
> This part, I don't understand. What do you want? Have you met `malloc` errors?

If we run `pre-commit` now, `clang-tidy` fails due to various errors, one of them was a `malloc` issue, though I can't find it right now

**Review by lan496 — APPROVED** [review]
Thank you so much for the quick fix! I confirm many warnings occur by running clang-tidy for all files, but it will be better to be addressed them in another PR.

Note for me: cmake-pre-commit-hooks creates a build directory (currently `_build-pre-commit` specified in .pre-commit-config.yaml) and `compile_commands.json`.

@atztogo I also think this PR is ready to be merged.

**Comment by atztogo** [comment]
Merged. Thanks @LecrisUT and @lan496.

**Comment by LecrisUT** [comment]
> Note for me: cmake-pre-commit-hooks creates a build directory (currently `_build-pre-commit` specified in .pre-commit-config.yaml) and `compile_commands.json`.

Yeah, it can also use the pre-configured build directories. I chose against it because it might not collect all source code, e.g. if it's build with `WITH_FORTRAN=OFF`.
